[Android] Implement chart/graph dependencies and ViewModel for Daily Reports screen
vikvelma/SkeletonPaymentApp-Senior pull request #1
Opened 2020-04-01 17:40 UTC by vikvelma

- Added chart/graph dependencies to gradle.
- Implemented viewModel class for `Daily Reports` screen.

2020-04-01 17:42 UTC, vikvelma commented on Android/app/src/main/java/com/imobile3/groovypayments/ui/chart/PieChartViewModel.java
> +    private ProductRepository mProductRepository;
Not sure which repository to be used!!

2020-04-02 13:00 UTC, HelloImKevo requested changes

2020-04-02 13:00 UTC, HelloImKevo commented on Android/build.gradle
> +
Can remove this extra newline, and the one below on line `22`

2020-04-02 13:00 UTC, HelloImKevo commented on Android/app/src/main/java/com/imobile3/groovypayments/ui/chart/PieChartViewModel.java
> +    private ProductRepository mProductRepository;
🤔 I think you could use the `CartRepository`, which would return a list of all the `Cart` models from the DB. The `Carts` represent orders that have been fulfilled for customers (and if you wanted further filtering, like for a Daily Report, I think there is a `CartEntity.DateCreated` field)

2020-04-02 14:10 UTC, vikvelma commented on Android/app/src/main/java/com/imobile3/groovypayments/ui/chart/PieChartViewModel.java
> +    private ProductRepository mProductRepository;
Cool, I assumed `CartRepository` only has the current order details!!

2020-04-02 20:06 UTC, HelloImKevo approved these changes
Looks great! I was able to patch this using:
```
git fetch git@github.com:vikvelma/SkeletonPaymentApp-Senior.git refs/pull/1/head:pr-daily-charts
```

2020-04-02 21:27 UTC, merged